AdminEmpl.Web/Pages/Empleados/Borrar.cshtml.cs
using AdminEmpl.Modelos;
using AdminEmpl.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdminEmpl.Web.Pages.Empleados
{
    public class BorrarModel : PageModel
    {
        private readonly IEmpleadoRepo empleadoRepo;
        public BorrarModel(IEmpleadoRepo empleadoRepo)
        {
            this.empleadoRepo = empleadoRepo;
        }
        [BindProperty]
        public Empleado Empleado { get; set; }
        public IActionResult OnGet(int id)
        {
            Empleado = empleadoRepo.ObtEmpleado(id);
            if (Empleado == null)
            {
                return RedirectToPage("/EmplNoEncont");
            }
            return Page();
        }
        public IActionResult OnPost()
        {
            Empleado empleadoBorr = empleadoRepo.BorrEmpleado(Empleado.Id);
            if (empleadoRepo == null)
            {
                return RedirectToPage("/EmplNoEncont");
            }
            return RedirectToPage("Index");
        }
    }
}

AdminEmpl.Web/Pages/Empleados/Index.cshtml.cs
using AdminEmpl.Modelos;
using AdminEmpl.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;

namespace AdminEmpl.Web.Pages.Empleados
{
    public class IndexModel : PageModel
    {
        private readonly IEmpleadoRepo empleadoRepo;
        public IEnumerable<Empleado> Empleados { get; set; }
        [BindProperty(SupportsGet = true)]
        public string TermBusq { get; set; }
        public IndexModel(IEmpleadoRepo empleadoRepo)
        {
            this.empleadoRepo = empleadoRepo;
        }
        public void OnGet()
        {
            Empleados = empleadoRepo.BuscEmpl(TermBusq);
        }
    }
}

AdminEmpl.Web/ViewComponents/CabContViewComponent.cs
using AdminEmpl.Modelos;
using AdminEmpl.Servicios;
using Microsoft.AspNetCore.Mvc;

namespace AdminEmpl.Web.ViewComponents
{
    public class CabContViewComponent : ViewComponent
    {
        private readonly IEmpleadoRepo empleadoRepo;

        public CabContViewComponent(IEmpleadoRepo empleadoRepo)
        {
            this.empleadoRepo = empleadoRepo;
        }
        public IViewComponentResult Invoke(Departamento? departNom = null)
        {
            var result = empleadoRepo.ContDepatEmpl(departNom);
            return View(result);
        }
    }
}

AdminEmpl.Web/Pages/Empleados/Borrar.cshtml
@page "{id}"
@model AdminEmpl.Web.Pages.Empleados.BorrarModel
@{
    ViewData["Title"] = "Borrar empleado";
    ViewData["MostrBot"] = false;
}
<h2>Borrar empleado</h2>
<h1>Confirmación de eliminación del empleado</h1>
<div class="alert alert-danger">
    <partial name="_MostrEmplParc" model="Model.Empleado" view-data="ViewData" />
    <h5>Estás seguro de eliminar al empleado - @Model.Empleado.Nombre</h5>
    <form method="post">
        <button type="submit" class="btn btn-danger">Sí</button>
        <a class="btn btn-primary" asp-page="/Empleados/Index">No</a>
    </form>
</div>

AdminEmpl.Web/Pages/Empleados/Detalles.cshtml
@page "empleado/ver/{id:min(1)}"
<!--Mediante el routin podemos esconder los parámetros que se están mandando por medio de direcciones personalizadas.-->
<!--Ejemplo: page "{variable}" -> page "{id}"-->
<!--Para evitar errores con la busqueda de datos por medio de ruteo podemos personalizar la ruta por medio de la propiedad page.-->
<!--Ejemplo: page "[NombParte]/{variable}" -> page "ver/{id}"-->
<!--Podemos añadir restricciones mediante una clase que contengan reglas de ruteo con podemos personalizar la entrada de usuarios.-->
<!--Ejemplo: Creen una clase desde el proyecto en donde se encuentra el sitio web.-->
<!--En el archivo startup.cs busquen las opciones de ruteo y añada la restricción.-->
<!--Aplicación page "[Direccionamiento personalizado *opcional*]/{Variable:[Nombre de la regla]}"-->
<!--page "empleado/ver/{id:even}"-->
@model AdminEmpl.Web.Pages.Empleados.DetallesModel
@{
    ViewData["Title"] = "Detalles";
    var fotodir = $"~/images/{Model.Empleado.FotoDir ?? "noimage.jpg"}";
}
<h1>Detalles</h1>
<div class="row justify-content-center m-3">
    <!--
    @if (!string.IsNullOrEmpty(Model.Msg))
    {
        <div class="col-sm-8">
            <div class="alert alert-primary">
                @Model.Msg
            </div>
        </div>
    }
    -->
    <!--
    @if (TempData["Msg"] != null)
    {
        <div class="col-sm-8">
            <div class="alert alert-primary">
                @TempData["Msg"]
            </div>
        </div>
    }
    -->
    @if (Model.Msg != null)
    {
        <div class="col-sm-8">
            <div class="alert alert-primary">
                @Model.Msg
            </div>
        </div>
    }
<div class="col-sm-8">
    @*await Component.InvokeAsync("CabCont",new { depart = Model.Empleado.Depart });*@
    <vc:cab-cont depart-nom="@Model.Empleado.Depart"></vc:cab-cont>
    
</div>
    <div class="col-sm-8">
        <div class="card">
            <div class="card-header">
                <h1>@Model.Empleado.Nombre</h1>
            </div>
            <div class="card-body text-center">
                <img class="card-img-top" src="@fotodir" asp-append-version="true" />
                <h4>Empleado ID: @Model.Empleado.Id</h4>
                <h4>Correo electronico: @Model.Empleado.CorreoE</h4>
                <h4>Departamento: @Model.Empleado.Depart</h4>
            </div>
            <div class="card-footer text-center">
                <a asp-page="index" class="btn btn-primary">Volver</a>
                <a asp-page="/Empleados/Editar" asp-route-ID="@Model.Empleado.Id" class="btn btn-primary m-1">Editar</a>
                <a asp-page="/Empleados/Borrar" asp-route-ID="@Model.Empleado.Id" class="btn btn-danger m-1">Borrar</a>
            </div>
        </div>
    </div>
</div>

AdminEmpl.Web/Pages/Empleados/Editar.cshtml
@page "{id:min(1)?}/{handler?}"
@model AdminEmpl.Web.Pages.Empleados.EditarModel
@{
    ViewData["Title"] = "Editar empleado";
    var fotodir = $"~/images/{Model.Empleado.FotoDir ?? "noimage.jpg"}";
    var pagEncab = Model.Empleado.Id > 0 ? "Editar" : "Agregar";
}
<h1>Notificación de preferencias</h1>
<form method="post" asp-page-handler="ActNotifPref">
    <div class="form-check">
        <input asp-for="Notif" class="form-check-input" />
        <label asp-for="Notif" class="form-check-label">Recibiste un correo donde notifica que tus detalles cambiaron.</label>
    </div>
    <button type="submit" class="btn btn-primary">Notificar de actualización de preferencias.</button>
    <!--
    @if (!string.IsNullOrEmpty(Model.Msg))
    {
        <div class="alert alert-primary">
            @Model.Msg
        </div>
    }
    -->
</form>
<h1>@pagEncab</h1>
<form method="post" class="mt-3" enctype="multipart/form-data" asp-page-handler="OnPost">
    <input hidden asp-for="Empleado.Id" />
    <input hidden asp-for="Empleado.FotoDir" />
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group row">
        <label asp-for="Empleado.Nombre" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Empleado.Nombre" class="form-control" placeholder="Nombre del empleado." />
            <span asp-validation-for="Empleado.Nombre" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Empleado.CorreoE" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Empleado.CorreoE" class="form-control" placeholder="Correo electronico del empleado." />
            <span asp-validation-for="Empleado.CorreoE" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Empleado.Depart" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <!--Sí queremos usar una lista seleccionable y tenemos datos podemos usar lo siguiente:-->
            <!--En la propiedad de la etiqueta select, asp-items le ponemos de valor Html.GetEnumSelectList<[Nombre de la lista]>().-->
            <!--Además debemos ir a _ViewImports.cshtml en donde se encuentran los using o librerias que itiliza la página.-->
            <select asp-for="Empleado.Depart" class="col-sm-2 col-form-label" asp-items="Html.GetEnumSelectList<Departamento>()">
                <option value="">Por favor selecciona el departamento.</option>
            </select>
            <span asp-validation-for="Empleado.Depart" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row col-sm-4 offset-4">
        <img class="imageThumbnail" src="@fotodir" asp-append-version="true" />
    </div>
    <div class="form-group row">
        <label asp-for="foto" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <input asp-for="foto" class="custom-file-input form-control" />
                <label class="custom-file-label">Seleccionar foto</label>
            </div>
        </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-page="/Empleados/Index" class="btn btn-danger">Cancelar</a>
        </div>
    </div>
    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var imagenname = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(imagenname);
                });
            });
        </script>
        <partial name="_ValidationScriptsPartial" />
    }
</form>

AdminEmpl.Web/Pages/Empleados/Index.cshtml
@page
<!--Mediante la propiedad page de Razor podemos asignarle una dirección especial de la página referente.-->
<!--Mediante el ruteo o consulta de direcciones, los sitios o aplicaciones web pueden realizar acciones como obtogar acceso a algo.-->
<!--Para cambiar la dirección de la página actual mediante Razor, se hace añadiendo un valor a la propiedad page.-->
<!--Ejemplo: page "[Dirección personalizada]" -> page "EmpleadosList"-->
<!--Tambien mediante el routin se puede hacer una busqueda mediante parámetros.-->
<!--Ejemplo: page "{propiedad}" -> page "{Nombre}"-->
<!--Además podemos hacer una implementación con exigir un tipo de parámetro o valor, es decir el valor del parámetro por ruteo puede ser específico.-->
<!--Ejemplo: page "{propiedad:tipovalor}" -> page "{Nombre:alpha}"-->
@model AdminEmpl.Web.Pages.Empleados.IndexModel
@{
	//Asignamos valores a la propiedad ViewData
    ViewData["Title"] = "Inicio empleados";
    ViewData["MostrBot"] = true;
}
<style>
    .btn {
        width: 75px;
    }
</style>
<form method="get">
    <div class="input-group">
        <input class="form-control" asp-for="TermBusq" />
        <div class="input-group-append">
            <button type="submit" class="btn btn-primary">Buscar</button>
        </div>
    </div>
</form>
@*await Component.InvokeAsync("CabCont");*@
<vc:cab-cont depart-nom="@null"></vc:cab-cont>
<h1 class="display-4">Empleados</h1>
<h3>@Model.Empleados.Count()</h3><!--Muestra la cantidad de empleados-->
<div class="card-deck">
    <!--Se realiza un ciclo mediante la cantidad de elementos que tiene el objeto Empleados.-->
    <!--Mediante Razor se invoca mediante el objeto referente a la parte del servidor.-->
    @foreach (var empleados in Model.Empleados)
    {
        /*
        var fotodir = $"~/images/{(empleados.FotoDir ?? "noimage.jpg")}";
        <div class="card m-3" style="min-width:18rem;max-width:30.5%;">
        <div class="card-header">
        <h3>@empleados.Nombre</h3>
        <h1>@empleados.Id</h1>
        </div>
        <img class="card-img-top imageThumbnail" src="@fotodir" asp-append-version="true" />
        <div class="card-footer text-center">
        <a asp-page="/Empleados/Detalles" asp-route-ID="@empleados.Id" class="btn btn-primary m-1">Ver</a>
        <a asp-page="/Empleados/Editar" asp-route-ID="@empleados.Id" class="btn btn-primary m-1">Editar</a>
        <a asp-page="/Empleados/Borrar" asp-route-ID="@empleados.Id" class="btn btn-danger m-1">Borrar</a>
        </div>
        </div>
        */
        <partial name="_MostrEmplParc" model="empleados" view-data="ViewData" />
    }
</div>